title: Yifan He @ UTsukuba
author: Yifan He
logo: /assets/img/logo.png
show_downloads: false
theme: jekyll-theme-minimal
google_analytics: UA-166069284-1
markdown: kramdown
kramdown:
  math_engine: mathjax
highlighter: rouge