title: HYF@ZUFE
author: Yifan He
show_downloads: false
theme: jekyll-theme-minimal
logo:
google_analytics: UA-166069284-1
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1